"""
Verdin iMX95 X1 (260-pin DDR4 SODIMM) pin assignment.

GENERATED by tools/extract_verdin_pinout.py from the Toradex
Verdin iMX95 hardware datasheet (doc 200007). Do not hand-edit -
re-run the extractor against a newer datasheet revision instead.

Names are the Verdin specification signal name, except on
Module-specific pins where the module-specific function is used
(this is what turns MSP_1 into LVDS0_CLK_N).
"""

# pin number -> signal name
X1_PINS = {
      1: "JTAG_1_TDI",        # top
      2: "ADC_1",             # bottom
      3: "JTAG_1_TRST#",      # top
      4: "ADC_2",             # bottom
      5: "JTAG_1_TDO",        # top
      6: "ADC_3",             # bottom
      7: "JTAG_1_VREF",       # top
      8: "ADC_4",             # bottom
      9: "JTAG_1_TCK",        # top
     10: "GND",               # bottom
     11: "GND",               # top
     12: "I2C_1_SDA",         # bottom
     13: "JTAG_1_TMS",        # top
     14: "I2C_1_SCL",         # bottom
     15: "PWM_1",             # top
     16: "PWM_2",             # bottom
     17: "GPIO_9_DSI",        # top
     18: "GND",               # bottom
     19: "PWM_3_DSI",         # top
     20: "CAN_1_TX",          # bottom
     21: "GPIO_10_DSI",       # top
     22: "CAN_1_RX",          # bottom
     23: "DSI_1_D3_N",        # top
     24: "CAN_2_TX",          # bottom
     25: "DSI_1_D3_P",        # top
     26: "CAN_2_RX",          # bottom
     27: "GND",               # top
     28: "GND",               # bottom
     29: "DSI_1_D2_N",        # top
     30: "I2S_1_BCLK",        # bottom
     31: "DSI_1_D2_P",        # top
     32: "I2S_1_SYNC",        # bottom
     33: "GND",               # top
     34: "I2S_1_D_OUT",       # bottom
     35: "DSI_1_CLK_N",       # top
     36: "I2S_1_D_IN",        # bottom
     37: "DSI_1_CLK_P",       # top
     38: "I2S_1_MCLK",        # bottom
     39: "GND",               # top
     40: "GND",               # bottom
     41: "DSI_1_D1_N",        # top
     42: "I2S_2_BCLK",        # bottom
     43: "DSI_1_D1_P",        # top
     44: "I2S_2_SYNC",        # bottom
     45: "GND",               # top
     46: "I2S_2_D_OUT",       # bottom
     47: "DSI_1_D0_N",        # top
     48: "I2S_2_D_IN",        # bottom
     49: "DSI_1_D0_P",        # top
     50: "GND",               # bottom
     51: "GND",               # top
     52: "QSPI_1_CLK",        # bottom
     53: "I2C_2_DSI_SDA",     # top
     54: "QSPI_1_CS#",        # bottom
     55: "I2C_2_DSI_SCL",     # top
     56: "QSPI_1_IO0",        # bottom
     57: "I2C_3_HDMI_SDA",    # top
     58: "QSPI_1_IO1",        # bottom
     59: "I2C_3_HDMI_SCL",    # top
     60: "QSPI_1_IO2",        # bottom
     61: "HDMI_1_HPD",        # top
     62: "QSPI_1_IO3",        # bottom
     63: "HDMI_1_CEC",        # top
     64: "QSPI_1_CS2#",       # bottom
     65: "GND",               # top
     66: "QSPI_1_DQS",        # bottom
     67: "HDMI_1_TXC_N",      # top
     68: "GND",               # bottom
     69: "HDMI_1_TXC_P",      # top
     70: "SD_1_D2",           # bottom
     71: "GND",               # top
     72: "SD_1_D3",           # bottom
     73: "HDMI_1_TXD0_N",     # top
     74: "SD_1_CMD",          # bottom
     75: "HDMI_1_TXD0_P",     # top
     76: "SD_1_PWR_EN",       # bottom
     77: "GND",               # top
     78: "SD_1_CLK",          # bottom
     79: "HDMI_1_TXD1_N",     # top
     80: "SD_1_D0",           # bottom
     81: "HDMI_1_TXD1_P",     # top
     82: "SD_1_D1",           # bottom
     83: "GND",               # top
     84: "SD_1_CD#",          # bottom
     85: "HDMI_1_TXD2_N",     # top
     86: "GND",               # bottom
     87: "HDMI_1_TXD2_P",     # top
     88: "LVDS0_CLK_N",       # bottom
     89: "GND",               # top
     90: "LVDS0_CLK_P",       # bottom
     91: "CSI_1_MCLK",        # top
     92: "TAMPER0",           # bottom
     93: "I2C_4_CSI_SDA",     # top
     94: "LVDS0_D0_N",        # bottom
     95: "I2C_4_CSI_SCL",     # top
     96: "LVDS0_D0_P",        # bottom
     97: "GND",               # top
     98: "GND",               # bottom
     99: "CSI_1_D3_P",        # top
    100: "LVDS0_D1_N",        # bottom
    101: "CSI_1_D3_N",        # top
    102: "LVDS0_D1_P",        # bottom
    103: "GND",               # top
    104: "TAMPER1",           # bottom
    105: "CSI_1_D2_P",        # top
    106: "LVDS0_D2_N",        # bottom
    107: "CSI_1_D2_N",        # top
    108: "LVDS0_D2_P",        # bottom
    109: "GND",               # top
    110: "GND",               # bottom
    111: "CSI_1_CLK_P",       # top
    112: "LVDS0_D3_N",        # bottom
    113: "CSI_1_CLK_N",       # top
    114: "LVDS0_D3_P",        # bottom
    115: "GND",               # top
    116: "MSP_13",            # bottom
    117: "CSI_1_D1_P",        # top
    118: "LVDS1_CLK_N",       # bottom
    119: "CSI_1_D1_N",        # top
    120: "LVDS1_CLK_P",       # bottom
    121: "GND",               # top
    122: "GND",               # bottom
    123: "CSI_1_D0_P",        # top
    124: "LVDS1_D0_N",        # bottom
    125: "CSI_1_D0_N",        # top
    126: "LVDS1_D0_P",        # bottom
    127: "GND",               # top
    128: "MSP_18",            # bottom
    129: "UART_1_RXD",        # top
    130: "LVDS1_D1_N",        # bottom
    131: "UART_1_TXD",        # top
    132: "LVDS1_D1_P",        # bottom
    133: "UART_1_RTS",        # top
    134: "GND",               # bottom
    135: "UART_1_CTS",        # top
    136: "LVDS1_D2_N",        # bottom
    137: "UART_2_RXD",        # top
    138: "LVDS1_D2_P",        # bottom
    139: "UART_2_TXD",        # top
    140: "MSP_23",            # bottom
    141: "UART_2_RTS",        # top
    142: "LVDS1_D3_N",        # bottom
    143: "UART_2_CTS",        # top
    144: "LVDS1_D3_P",        # bottom
    145: "GND",               # top
    146: "GND",               # bottom
    147: "UART_3_RXD",        # top
    148: "GPIO_IO34",         # bottom
    149: "UART_3_TXD",        # top
    150: "GPIO_IO33",         # bottom
    151: "UART_4_RXD",        # top
    152: "GPIO_IO04",         # bottom
    153: "UART_4_TXD",        # top
    154: "GPIO_IO07",         # bottom
    155: "USB_1_EN",          # top
    156: "SD3_CLK",           # bottom
    157: "USB_1_OC#",         # top
    158: "GND",               # bottom
    159: "USB_1_VBUS",        # top
    160: "SD3_CMD",           # bottom
    161: "USB_1_ID",          # top
    162: "SD3_DATA0",         # bottom
    163: "USB_1_D_N",         # top
    164: "SD3_DATA1",         # bottom
    165: "USB_1_D_P",         # top
    166: "SD3_DATA2",         # bottom
    167: "GND",               # top
    168: "SD3_DATA3",         # bottom
    169: "USB_2_SSTX_N",      # top
    170: "GND",               # bottom
    171: "USB_2_SSTX_P",      # top
    172: "ADC",               # bottom
    173: "GND",               # top
    174: "ADC",               # bottom
    175: "USB_2_SSRX_N",      # top
    176: "MSP_38",            # bottom
    177: "USB_2_SSRX_P",      # top
    178: "USB1_TX1_N",        # bottom
    179: "GND",               # top
    180: "USB1_TX1_P",        # bottom
    181: "USB_2_D_N",         # top
    182: "GND",               # bottom
    183: "USB_2_D_P",         # top
    184: "USB1_RX1_N",        # bottom
    185: "USB_2_EN",          # top
    186: "USB1_RX1_P",        # bottom
    187: "USB_2_OC#",         # top
    188: "PMIC_PGOOD",        # bottom
    189: "ETH_2_RGMII_INT#",  # top
    190: "ADC_IN4",           # bottom
    191: "ETH_2_RGMII_MDIO",  # top
    192: "ADC_IN5",           # bottom
    193: "ETH_2_RGMII_MDC",   # top
    194: "GND",               # bottom
    195: "GND",               # top
    196: "SPI_1_CLK",         # bottom
    197: "ETH_2_RGMII_RXC",   # top
    198: "SPI_1_MISO",        # bottom
    199: "ETH_2_RGMII_RX_CTL",  # top
    200: "SPI_1_MOSI",        # bottom
    201: "ETH_2_RGMII_RXD_0",  # top
    202: "SPI_1_CS",          # bottom
    203: "ETH_2_RGMII_RXD_1",  # top
    204: "GND",               # bottom
    205: "ETH_2_RGMII_RXD_2",  # top
    206: "GPIO_1",            # bottom
    207: "ETH_2_RGMII_RXD_3",  # top
    208: "GPIO_2",            # bottom
    209: "GND",               # top
    210: "GPIO_3",            # bottom
    211: "ETH_2_RGMII_TX_CTL",  # top
    212: "GPIO_4",            # bottom
    213: "ETH_2_RGMII_TXC",   # top
    214: "PWR_1V8_MOCI",      # bottom
    215: "ETH_2_RGMII_TXD_3",  # top
    216: "GPIO_5_CSI",        # bottom
    217: "ETH_2_RGMII_TXD_2",  # top
    218: "GPIO_6_CSI",        # bottom
    219: "ETH_2_RGMII_TXD_1",  # top
    220: "GPIO_7_CSI",        # bottom
    221: "ETH_2_RGMII_TXD_0",  # top
    222: "GPIO_8_CSI",        # bottom
    223: "GND",               # top
    224: "GND",               # bottom
    225: "ETH_1_MDI0_P",      # top
    226: "PCIE_1_CLK_N",      # bottom
    227: "ETH_1_MDI0_N",      # top
    228: "PCIE_1_CLK_P",      # bottom
    229: "GND",               # top
    230: "GND",               # bottom
    231: "ETH_1_MDI1_N",      # top
    232: "PCIE_1_L0_RX_N",    # bottom
    233: "ETH_1_MDI1_P",      # top
    234: "PCIE_1_L0_RX_P",    # bottom
    235: "ETH_1_LED_1",       # top
    236: "GND",               # bottom
    237: "ETH_1_LED_2",       # top
    238: "PCIE_1_L0_TX_N",    # bottom
    239: "ETH_1_MDI2_P",      # top
    240: "PCIE_1_L0_TX_P",    # bottom
    241: "ETH_1_MDI2_N",      # top
    242: "GND",               # bottom
    243: "GND",               # top
    244: "PCIE_1_RESET#",     # bottom
    245: "ETH_1_MDI3_N",      # top
    246: "CTRL_RECOVERY_MICO#",  # bottom
    247: "ETH_1_MDI3_P",      # top
    248: "CTRL_PWR_BTN_MICO#",  # bottom
    249: "VCC_BACKUP",        # top
    250: "CTRL_FORCE_OFF_MOCI#",  # bottom
    251: "VCC",               # top
    252: "CTRL_WAKE1_MICO#",  # bottom
    253: "VCC",               # top
    254: "CTRL_PWR_EN_MOCI",  # bottom
    255: "VCC",               # top
    256: "CTRL_SLEEP_MOCI#",  # bottom
    257: "VCC",               # top
    258: "CTRL_RESET_MOCI#",  # bottom
    259: "VCC",               # top
    260: "CTRL_RESET_MICO#",  # bottom
}

GND_PINS = [10, 11, 18, 27, 28, 33, 39, 40, 45, 50, 51, 65, 68, 71, 77, 83, 86, 89, 97, 98, 103, 109, 110, 115, 121, 122, 127, 134, 145, 146, 158, 167, 170, 173, 179, 182, 194, 195, 204, 209, 223, 224, 229, 230, 236, 242, 243]

VCC_PINS = [251, 253, 255, 257, 259]

# Table 23 - the display link this board is built around.
LVDS_PINS = {
     88: "LVDS0_CLK_N",
     90: "LVDS0_CLK_P",
     94: "LVDS0_D0_N",
     96: "LVDS0_D0_P",
    100: "LVDS0_D1_N",
    102: "LVDS0_D1_P",
    106: "LVDS0_D2_N",
    108: "LVDS0_D2_P",
    112: "LVDS0_D3_N",
    114: "LVDS0_D3_P",
    118: "LVDS1_CLK_N",
    120: "LVDS1_CLK_P",
    124: "LVDS1_D0_N",
    126: "LVDS1_D0_P",
    130: "LVDS1_D1_N",
    132: "LVDS1_D1_P",
    136: "LVDS1_D2_N",
    138: "LVDS1_D2_P",
    142: "LVDS1_D3_N",
    144: "LVDS1_D3_P",
}
